stripe_project/items/urls.py
from django.urls import path

from .views import (CancelView, CreateOrderCheckoutSessionView,
                    CreateSingleCheckoutSessionView, CustomPaymentView,
                    IndexView, ItemPageView, ShowCart, StripeIntentView,
                    SuccessView, add_to_cart, delete_from_cart, stripe_webhook)

app_name = 'items'

urlpatterns = [
    path('cart/add/<pk>/', add_to_cart, name='add-to-cart'),
    path('cart/delete/<pk>/', delete_from_cart, name='delete-from-cart'),
    path('cart/', ShowCart.as_view(), name='cart'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/', SuccessView.as_view(), name='success'),
    path('buy/<pk>/', CreateSingleCheckoutSessionView.as_view(), name='buy'),
    path('get/<pk>/', ItemPageView.as_view(), name='get-item'),
    path('order/<pk>/', CreateOrderCheckoutSessionView.as_view(),
         name='buy-order'),
    path('webhooks/stripe/', stripe_webhook, name='stripe-webhook'),
    path('create-payment-intent/<pk>/', StripeIntentView.as_view(),
         name='create-payment-intent'),
    path('custom-payment/', CustomPaymentView.as_view(),
         name='custom-payment'),
    path('', IndexView.as_view(), name='index'),
]

stripe_project/stripe_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

static_urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('items.urls', namespace='items')),
    path('', include(static_urlpatterns)),
]

stripe_project/users/urls.py
from django.urls import include, path

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('', include('django.contrib.auth.urls')),
]

stripe_project/items/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Item(models.Model):
    name = models.CharField(
        max_length=256,
        verbose_name='Название товара')
    description = models.TextField(verbose_name='Описание товара')
    stripe_product_id = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['name', ]

    def __str__(self):
        return self.name


class Tax(models.Model):
    name = models.CharField(
        max_length=256,
        verbose_name='Название налога')
    rate = models.FloatField(
        verbose_name='Размер налога')

    class Meta:
        verbose_name = 'Налог'
        verbose_name_plural = 'Налоги'

    def __str__(self):
        return f'{self.name} в штате Техас: {self.rate}%'

    def get_display_tax(self):
        return self.rate


class Discount(models.Model):
    name = models.CharField(
        max_length=256,
        verbose_name='Название скидки')
    size = models.IntegerField(
        verbose_name='Размер скидки')
    stripe_coupon_id = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'

    def __str__(self):
        return f'{self.name}: {self.size}%'

    def get_display_tax(self):
        return self.size


class Price(models.Model):
    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        verbose_name='Товар')
    stripe_price_id_usd = models.CharField(max_length=100)
    stripe_price_id_eur = models.CharField(max_length=100)
    price_usd = models.IntegerField(
        default=0,
        verbose_name='Цена в долларах')
    price_eur = models.IntegerField(
        default=0,
        verbose_name='Цена в евро')
    tax = models.ForeignKey(
        Tax,
        on_delete=models.DO_NOTHING,
        verbose_name='Налог')
    discount = models.ForeignKey(
        Discount,
        on_delete=models.DO_NOTHING,
        verbose_name='Скидка',
        blank=True,
    )

    class Meta:
        verbose_name = 'Цена'
        verbose_name_plural = 'Цены'

    def get_display_price_usd(self):
        return "{0:.2f}".format(self.price_usd / 100)

    def get_display_price_eur(self):
        return "{0:.2f}".format(self.price_eur / 100)


class Order(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Покупатель')
    prices = models.ManyToManyField(
        Price,
        verbose_name='Цены в заказе',
        through='PriceInOrder',
        related_name='orders'
    )
    total_usd = models.IntegerField(default=0)
    total_eur = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class PriceInOrder(models.Model):
    """Вспомогательная модель для сбора заказа из нескольких товаров."""
    price = models.ForeignKey(
        Price,
        verbose_name='Цена',
        on_delete=models.CASCADE
    )
    order = models.ForeignKey(
        Order,
        verbose_name='Заказ',
        on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField(
        default=0)

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

    def __str__(self):
        return self.price.item.name

    def get_cost_usd(self):
        return "{0:.2f}".format(self.price.price_usd * self.quantity / 100)

    def get_cost_eur(self):
        return "{0:.2f}".format(self.price.price_eur * self.quantity / 100)

stripe_project/items/views.py
import json

import stripe
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from .models import Discount, Item, Order, Price, PriceInOrder

stripe.api_key = settings.STRIPE_SECRET_KEY

DOMAIN = 'http://158.160.36.223/'


class SuccessView(TemplateView):
    template_name = 'items/success.html'


class CancelView(TemplateView):
    template_name = 'items/cancel.html'


class CreateSingleCheckoutSessionView(View):
    def post(self, request, *args, **kwargs):
        price = Price.objects.get(id=self.kwargs['pk'])
        discount = price.discount.stripe_coupon_id
        currency = request.POST.get('currency')
        domain = DOMAIN
        if settings.DEBUG:
            domain = 'http://127.0.0.1:8000'
        if currency == 'usd':
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=[
                    {
                        'price': price.stripe_price_id_usd,
                        'quantity': 1,
                    },
                ],
                mode='payment',
                discounts=[{'coupon': discount}],
                automatic_tax={'enabled': True},
                shipping_address_collection={
                    'allowed_countries': ['US'],
                },
                success_url=domain + '/success/',
                cancel_url=domain + '/cancel/',
            )
        else:
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=[
                    {
                        'price': price.stripe_price_id_eur,
                        'quantity': 1,
                    },
                ],
                mode='payment',
                discounts=[{'coupon': discount}],
                automatic_tax={'enabled': True},
                shipping_address_collection={
                    'allowed_countries': ['US'],
                },
                success_url=domain + '/success/',
                cancel_url=domain + '/cancel/',
            )
        return redirect(checkout_session.url)


class CreateOrderCheckoutSessionView(View):
    def post(self, request, *args, **kwargs):
        order = Order.objects.get(id=self.kwargs['pk'])
        prices = PriceInOrder.objects.filter(order=order)
        discount = Discount.objects.get(pk=1).stripe_coupon_id
        currency = request.POST.get('currency')
        line_items_list = []
        if currency == 'usd':
            for price in prices:
                line_items_list.append(
                    {
                        'price': price.price.stripe_price_id_usd,
                        'quantity': price.quantity,
                    }
                )
        else:
            for price in prices:
                line_items_list.append(
                    {
                        'price': price.price.stripe_price_id_eur,
                        'quantity': price.quantity,
                    }
                )
        domain = DOMAIN
        if settings.DEBUG:
            domain = 'http://127.0.0.1:8000'
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=line_items_list,
            mode='payment',
            discounts=[{'coupon': discount}],
            automatic_tax={'enabled': True},
            shipping_address_collection={
                'allowed_countries': ['US'],
            },
            success_url=domain + '/success/',
            cancel_url=domain + '/cancel/',
        )
        return redirect(checkout_session.url)


class IndexView(TemplateView):
    template_name = 'items/index.html'

    def get_context_data(self, **kwargs):
        prices = Price.objects.all()
        context = super(IndexView,
                        self).get_context_data(**kwargs)
        context.update({
            "prices": prices,
        })
        return context


class ItemPageView(TemplateView):
    template_name = 'items/item.html'

    def get_context_data(self, **kwargs):
        price = Price.objects.get(id=self.kwargs['pk'])
        context = super(ItemPageView,
                        self).get_context_data(**kwargs)
        context.update({
            "price": price,
        })
        return context


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        return HttpResponse(status=400)

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        customer_email = session['customer_details']['email']
        payment_intent = session['payment_intent']

        # TODO - send an email to the customer

    elif event['type'] == 'payment_intent.succeeded':
        intent = event['data']['object']
        stripe_customer_id = intent["customer"]
        stripe_customer = stripe.Customer.retrieve(stripe_customer_id)
        customer_email = stripe_customer['email']
        price_id = intent["metadata"]["price_id"]
        price = Price.objects.get(id=price_id)
        item = price.item

    return HttpResponse(status=200)


class StripeIntentView(View):
    def post(self, request, *args, **kwargs):
        try:
            req_json = json.loads(request.body)
            customer = stripe.Customer.create(email=req_json['email'])
            price = Price.objects.get(id=self.kwargs['pk'])
            intent = stripe.PaymentIntent.create(
                amount=price.price,
                currency='usd',
                customer=customer['id'],
                metadata={
                    'price_id': price.id
                }
            )
            return JsonResponse({
                'clientSecret': intent['client_secret']
            })
        except Exception as e:
            return JsonResponse({'error': str(e)})


class CustomPaymentView(TemplateView):
    template_name = 'custom_payment.html'

    def get_context_data(self, **kwargs):
        item = Item.objects.get(name=self.name)
        prices = Price.objects.filter(item=item)
        context = super(CustomPaymentView, self).get_context_data(**kwargs)
        context.update({
            "item": item,
            "prices": prices,
            "STRIPE_PUBLIC_KEY": settings.STRIPE_PUBLIC_KEY
        })
        return context


def add_to_cart(request, pk):
    order, created = Order.objects.get_or_create(user=request.user)
    price = get_object_or_404(Price, pk=pk)
    pricesinorder, created = PriceInOrder.objects.get_or_create(
        price=price,
        order=order)
    pricesinorder.quantity += 1
    pricesinorder.save()
    return redirect('items:cart')


def delete_from_cart(request, pk):
    order = get_object_or_404(Order, user=request.user)
    price = get_object_or_404(Price, pk=pk)
    priceinorder = get_object_or_404(PriceInOrder, price=price, order=order)
    priceinorder.quantity -= 1
    if priceinorder.quantity > 0:
        priceinorder.save()
    else:
        priceinorder.delete()
    messages.success(request, 'Cart updated!')
    return redirect('items:cart')


class ShowCart(TemplateView):
    template_name = 'items/cart.html'

    def get_context_data(self, **kwargs):
        order, created = Order.objects.get_or_create(user=self.request.user)
        if created:
            context = super(ShowCart,
                            self).get_context_data(**kwargs)
            context.update({
                'message': 'Ваша корзина пуста, скорее приступайте к покупкам!'
            })
            return context
        else:
            prices = PriceInOrder.objects.filter(order=order)
            total_usd = 0
            total_eur = 0
            for i in prices:
                total_usd += float(i.get_cost_usd())
                total_eur += float(i.get_cost_eur())
            order.total_usd = total_usd
            order.total_eur = total_eur
            context = super(ShowCart,
                            self).get_context_data(**kwargs)
            context.update({
                'order': order,
                'prices': prices,
                'total_usd': "{:.2f}".format(total_usd),
                'total_eur': "{:.2f}".format(total_eur),
            })
            return context

stripe_project/templates/items/cancel.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
<html>
{% block head %}
<head>
  <title>Checkout canceled</title>
</head>
{% endblock %}

{% block content %}
<body>
  <div class="message">
    <p> Забыли добавить что-то в корзину? Загляните в наш каталог и не забудьте вернуться к заказу! </p>
    <a href="{% url 'items:index'%}"> Вернуться к списку товаров </a>
  </div>
</body>
{% endblock %}
</html>

stripe_project/templates/items/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>

{% block head %}
<head>
    <title> Your shopping cart </title>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
</head>
{% endblock %}

{% block content %}
<body>
  {% if message %}
  <div class="message"> <p> {{ message }} </p> </div>
  {% else %}
    {% for price in prices %}
      <div class="product-card-cart">
        <h2 style="float: left">{{ price }}</h2>
          <select name="currency" class="form-control" id="price_stripe_id" style="float: left; margin: 30px 20px;">
            <option disabled> Цена товара </option>
            <option value="usd"> ${{ price.get_cost_usd }} </option>
            <option value="eur"> €{{ price.get_cost_eur }} </option>
          </select>
        <h3 style="float: right; margin: 20px 5px"> количество: {{ price.quantity }}</h3>
        <form action="{% url 'items:add-to-cart' price.price.id %}" method="POST" style="float: left; margin: 20px 5px;">
          {% csrf_token %}
          <button type="submit"> добавить </button>
        </form>
        <form action="{% url 'items:delete-from-cart' price.price.id %}" method="POST" style="float: left; margin: 20px 5px">
          {% csrf_token %}
          <button type="submit" style="margin: 5px 0"> удалить </button>
        </form>
      </div>
    {% endfor %}
    <div class="total">
      <h2 style="float: left"> Общая сумма покупки: </h2>
      <form action="{% url 'items:buy-order' order.id %}" method="POST" style="float: left; margin: 20px 30px 0 30px;">
        {% csrf_token %}
        <select name="currency" class="form-control" id="total">
          <option disabled> Выберите валюту оплаты </option>
          <option value="usd"> ${{ total_usd }} </option>
          <option value="eur"> €{{ total_eur}} </option>
        </select>
        <button type="submit" style="margin-left: 20px"> оплатить </button>
      </form>
    </div>
  {% endif %}
</body>
{% endblock %}
</html>

stripe_project/templates/items/custom_payment.html
<!DOCTYPE html>
<html>

<head>
    <title>Custom payment</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
</head>
    
<body>
    <section>
        <div class="product">
            <div class="description">
                <h3>{{ item.name }}</h3>
                <hr />
                <select>
                    {% for price in prices %}
                    <option value="{{ price.id }}">${{ price.get_display_price }}</option>
                    {% endfor %}
                </select>
            </div>

            <form id="payment-form">
                {% csrf_token %}
                <input type="text" id="email" placeholder="Email address" />
                <div id="card-element">
                    <!--Stripe.js injects the Card Element-->
                </div>
                <button id="submit">
                    <div class="spinner hidden" id="spinner"></div>
                    <span id="button-text">Pay</span>
                </button>
                <p id="card-error" role="alert"></p>
                <p class="result-message hidden">
                    Payment succeeded, see the result in your
                    <a href="https://dashboard.stripe.com" target="_blank">Stripe dashboard.</a> Refresh the page to
                    pay again.
                </p>
            </form>
        </div>
    </section>
    <script>
        var csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
        document.querySelector("button").disabled = true;
        var elements = stripe.elements();
        var style = {
            base: {
            color: "#32325d",
            fontFamily: 'Arial, sans-serif',
            fontSmoothing: "antialiased",
            fontSize: "16px",
            "::placeholder": {
            color: "#32325d"
           }
        },
        invalid: {
        fontFamily: 'Arial, sans-serif',
        color: "#fa755a",
        iconColor: "#fa755a"
            }
        };
        var card = elements.create("card", { style: style });
        // Stripe injects an iframe into the DOM
        card.mount("#card-element");
        card.on("change", function (event) {
            // Disable the Pay button if there are no card details in the Element
            document.querySelector("button").disabled = event.empty;
            document.querySelector("#card-error").textContent = event.error ? event.error.message : "";
        });
        var form = document.getElementById("payment-form");
        form.addEventListener("submit", function(event) {
            event.preventDefault();
            var selectedPrice = document.getElementById("prices").value
            // Complete payment when the submit button is clicked
            fetch(`/create-payment-intent/${selectedPrice}/`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                'X-CSRFToken': csrftoken
            },
            body: JSON.stringify({
                email: document.getElementById('email').value
            })
            })
            .then(function(result) {
                return result.json();
            })
            .then(function(data) {
                payWithCard(stripe, card, data.clientSecret);
            });
        });

// Calls stripe.confirmCardPayment
// If the card requires authentication Stripe shows a pop-up modal to
// prompt the user to enter authentication details without leaving your page.
        var payWithCard = function(stripe, card, clientSecret) {
            loading(true);
            stripe
            .confirmCardPayment(clientSecret, {
                payment_method: {
                card: card
                }
            })
            .then(function(result) {
                if (result.error) {
        // Show error to your customer
                showError(result.error.message);
                } else {
        // The payment succeeded!
                orderComplete(result.paymentIntent.id);
                }
            });
        };
/* ------- UI helpers ------- */
// Shows a success message when the payment is complete
        var orderComplete = function(paymentIntentId) {
            loading(false);
            document
            .querySelector(".result-message a")
            .setAttribute(
                "href",
                "https://dashboard.stripe.com/test/payments/" + paymentIntentId
            );      
            document.querySelector(".result-message").classList.remove("hidden");
            document.querySelector("button").disabled = true;
        };
// Show the customer the error from Stripe if their card fails to charge
        var showError = function(errorMsgText) {
            loading(false);
            var errorMsg = document.querySelector("#card-error");
            errorMsg.textContent = errorMsgText;
            setTimeout(function() {
            errorMsg.textContent = "";
            }, 4000);
        };
// Show a spinner on payment submission
        var loading = function(isLoading) {
            if (isLoading) {
    // Disable the button and show a spinner
            document.querySelector("button").disabled = true;
            document.querySelector("#spinner").classList.remove("hidden");
            document.querySelector("#button-text").classList.add("hidden");
            } else {
            document.querySelector("button").disabled = false;
            document.querySelector("#spinner").classList.add("hidden");
            document.querySelector("#button-text").classList.remove("hidden");
            }
        };
    </script>
</body>

</html>

stripe_project/templates/items/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>

{% block head %}
<head>
    <title>Buy cool new product</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
</head>
{% endblock %}

{% block content %}
<body>
    <br>
    <div class="header">
        {% if request.user.is_authenticated %}
            <a href="{% url 'items:cart'%}"> Моя корзина</a>
            <a href="{% url 'users:logout'%}"> Выйти </a>
        {% else %}
            <a href="{% url 'users:login' %}"> Войти </a>
            <a href="{% url 'users:signup' %}"> Зарегистрироваться </a>
        {% endif %}
    </div>
    {% for price in prices %}
      <div class="product-card">
        <h2>{{ price.item.name }}</h2>
        <h3>{{ price.item.description }}</h3>
        <div>
          <h5>{{ price.tax }}</h5>
          <h5>{{ price.discount }}</h5>
          <form action="{% url 'items:buy' price.id %}" method="POST" style="float: left">
            {% csrf_token %}
            <select name="currency" class="form-control" id="price_stripe_id">
              <option disabled> Цена товара </option>
              <option value="usd"> ${{ price.get_display_price_usd }} </option>
              <option value="eur"> €{{ price.get_display_price_eur }} </option>
            </select>
            <button type="submit"> К оплате </button>
          </form>
          <form action="{% url 'items:get-item' price.id %}" style="float: right;">
            <button> Подробнее </button>
          </form>
          {% if request.user.is_authenticated %}
            <form action="{% url 'items:add-to-cart' price.id %}" method="POST" style="float: right;">
              {% csrf_token %}
              <button type="submit"> Добавить в корзину </button>
            </form>
          {% else %}
            <form action="{% url 'users:login' %}" style="float: right;">
              <button> Авторизуйтесь для добавления в корзину </button>
            </form>
          {% endif %}
        </div>
      </div>    
    {% endfor %}
</body>
{% endblock %}
</html>

stripe_project/templates/items/item.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>

{% block head %}
<head>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
</head>
{% endblock %}

{% block content %}
<body>
  <div class="product-card" style="margin: 30% 70%">
    <h2>{{ price.item.name }}</h2>
    <h3>{{ price.item.description }}</h3>
    <h5>{{ price.tax }}</h5>
    <h5>{{ price.discount }}</h5>
      <form action="{% url 'items:buy' price.id %}" method="POST" style="float:left; margin-left: 30px">
        {% csrf_token %}
        <select name="currency" class="form-control" id="price_stripe_id">
          <option disabled> Цена товара </option>
          <option value="usd"> <h5>${{ price.get_display_price_usd }}</h5> </option>
          <option value="eur"> <h5>€{{ price.get_display_price_eur }}</h5> </option>
        </select>
        <button type="submit"> К оплате </button>
      </form>
      {% if request.user.is_authenticated %}
        <form action="{% url 'items:add-to-cart' price.id %}" method="POST" style="float: left">
          {% csrf_token %}
          <button type="submit"> Добавить в корзину </button>
        </form>
      {% else %}
        <a href="{% url 'users:login' %}"> Авторизуйтесь для добавления в корзину </a>
      {% endif %}
  </div>
</body>
{% endblock %}
</html>

stripe_project/templates/items/success.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html>

{% block head %}
<head>
  <title>Thanks for your order!</title>
</head>
{% endblock %}

{% block content %}
<body>
  <div class="message">
    <p> We appreciate your business! If you have any questions, please email </p>
    <a href="mailto:orders@example.com">orders@example.com</a>.
  </div>
</body>
{% endblock %}
</html>